name: SonarCloud Manual PR Gate

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install SonarCloud CLI Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          export PATH="$PWD/sonar-scanner-5.0.1.3006-linux/bin:$PATH"

      - name: Run SonarCloud Analysis
        run: |
          sonar-scanner \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Wait for SonarCloud Analysis to Finish
        run: sleep 20

      - name: Get Quality Gate Status
        id: quality_gate
        run: |
          SONAR_STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=evoraglobal_aeris-web" | jq -r '.projectStatus.status')
          echo "Quality Gate status: $SONAR_STATUS"
          if [ "$SONAR_STATUS" != "OK" ]; then
            echo "❌ Quality Gate failed"
            exit 1
          else
            echo "✅ Quality Gate passed"
          fi
