name: SonarCloud Manual PR Gate

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: ${{ secrets.SONAR_ORG }}
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          token: ${{ secrets.SONAR_TOKEN }}

      - name: Wait for SonarCloud Analysis to Finish
        run: sleep 20  # Simple wait to allow background processing

      - name: Get Quality Gate Status
        id: quality_gate
        run: |
          SONAR_STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" | jq -r '.projectStatus.status')
          echo "Quality Gate status: $SONAR_STATUS"
          if [ "$SONAR_STATUS" != "OK" ]; then
            echo "❌ Quality Gate failed"
            exit 1
          else
            echo "✅ Quality Gate passed"
          fi
